@startuml

!$GLOBAL_BASEPATH = ../_global

!include $GLOBAL_BASEPATH/style/theme/mermaid-dark-theme.iuml
!include $GLOBAL_BASEPATH/functional/sequence/commonSequenceFunctions.iuml

skinparam MaxMessageSize 250

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response

@enduml