@startuml

!$GLOBAL_BASEPATH = ../_global

!include /workspace/docs/_global/style/theme/mermaid-dark-theme.iuml
!include /workspace/docs/_global/functional/sequence/commonSequenceFunctions.iuml

skinparam MaxMessageSize 250

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response

@enduml